version: '3'

services:
  
  app:
    build: 
      context: ./node
    container_name: app
    image: franciscosf/node
    networks:
      - network-fsf 
    volumes:
      - ./node:/user/src/app
    tty: true
    #ports:
    #  - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - network-fsf

  nginx:
    build: 
      context: ./nginx
    image: franciscosf/nginx
    container_name: nginx
    networks: 
      - network-fsf
    ports: 
      - "8080:80"
    depends_on:
      - app
      
networks:
  network-fsf:
    driver: bridge