version: '3'

services:
  
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: docker-entrypoint.sh /meu_docker-entrypoint.sh node index.js
    image: franciscosf/node
    networks:
      - network-fsf
    volumes:
      - ./node:/user/src/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - network-fsf
    healthcheck:
      test: "mysqladmin ping -u root --password=$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  nginx:
    build: 
      context: ./nginx
    image: franciscosf/nginx
    container_name: nginx
    networks: 
      - network-fsf
    ports: 
      - "8080:80"
    depends_on:
      - app
      
networks:
  network-fsf:
    driver: bridge